language: cpp
sudo: false

git:
   depth: 3

addons:
   apt:
      sources:
         # add the LLVM 6.0 repository
         - llvm-toolchain-trusty-6.0
         # add a repository with a more recent version of the libstdc++ package
         # (required for LLVM 6.0)
         - ubuntu-toolchain-r-test
      packages:
         - llvm-6.0-dev
         - clang-6.0

install :
   - make compile -j2

script :
   - make unittest -j2
   - make regression
   - cd doc/example; make run
